---
# === Unmount ===

  - name: " Deploy  | Releasing multipath "
    script: "mpath.sh release {{ devmap }}/{{ item.id }}"
    register: released
    when: map == false
    ignore_errors: true
    with_items: "{{ wwid }}"

  - name: " Deploy | lazy unmount "
    command: "umount -l {{ devmap }}/{{ item.id }}"
    register: lazyed
    with_items: "{{ wwid }}"
    ignore_errors: true
    when: 
      - map == false
      - released|succeeded

  - name: " Deploy | Clearing fstab "
    mount:
      path: "/mnt/{{ item.alias }}"
      src: "{{ devmap }}/{{ item.id }}"
      fstype: "{{ filesystem }}"
      state: absent
    with_items: "{{ wwid }}"
    when:
      - map == false
      - released|succeeded

  - name: " Deploy | flush multipath "
    command: "multipath -f {{ devmap }}/{{ item.id }}"
    register: flushed
    with_items: "{{ wwid }}"
    notify:
      - "stop iscsid"
      - "stop iscsi"
      - "stop multipathd"
    when:
      - map == false
      - released|succeeded
      - lazyed|succeeded

  - name: " Result | unmount status "
    #fail:
    debug:
      msg: "There is no device to unmount here"
    when:
      - map == false
      - released|failed 
